/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    CREATE_STREAM: "CREATE_STREAM",
    CREATE_STREAM_SUCCESS: "CREATE_STREAM_SUCCESS",
    FETCH_STREAMS:"FETCH_STREAMS",
    FETCH_STREAMS_SUCCESS:"FETCH_STREAMS_SUCCESS",
    FETCH_STREAM:"FETCH_STREAM",
    FETCH_STREAM_SUCCESS:"FETCH_STREAM_SUCCESS",
    UPDATE_STREAM:"UPDATE_STREAM",
    UPDATE_STREAM_SUCCESS:"UPDATE_STREAM_SUCCESS",
    DELETE_STREAM:"DELETE_STREAM",
}